services:
  tests:
    build: "."
    volumes:
      - "./package.json:/exercises/package.json"
      - "./package-lock.json:/exercises/package-lock.json"
      - "./Wordle:/exercises/Wordle"
      - "./Wordle.Tests:/exercises/Wordle.Tests"
    working_dir: "/exercises"
    command: ["npm", "run", "test"]
    init: true # to ensure signal handling works (and you can kill the container with ctrl-c)
